name = "clickup-workers"
main = "src/worker.js"
compatibility_date = "2024-10-01"

[vars]
# No plain vars by default; secrets set with `wrangler secret put`

[triggers]
crons = ["0 9 * * MON"]

[env.production]
name = "clickup-workers"

[env.staging]
name = "clickup-workers-staging"


